# Generated by Django 3.1.2 on 2020-10-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_workout_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date']},
        ),
    ]
